version: "3.8"

services:
  ### BASE DE DATOS ###
  db:
    image: mysql:8.0
    container_name: app_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secret
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./BD:/docker-entrypoint-initdb.d:ro
    command: --default-authentication-plugin=mysql_native_password

  ### BACKEND - SYMFONY + PHP-FPM ###
  backend:
    image: jaguamanp96/symfony_backend:1.0.0
    container_name: symfony_backend
    volumes:
      - ./backend:/var/www/html
      - var_cache:/var/www/html/var
    environment:
      APP_ENV: prod
      DATABASE_URL: "mysql://app_user:secret@db:3306/app_db?serverVersion=8.0"
    depends_on:
      - db
    expose:
      - "9000"

  ### NGINX SYMFONY ###
  nginx_backend:
    image: nginx:alpine
    container_name: nginx_symfony
    depends_on:
      - backend
    volumes:
      - ./backend/nginx/symfony.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/public:/var/www/html/public:ro
    ports:
      - "8001:80"

  ### FRONTEND - REACT + NGINX ###
  frontend:
    image: jaguamanp96/react_frontend:1.0.0
    container_name: react_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/nginx/react.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
  var_cache:

